export { default as logoImg } from './logo.png'
export {default as bnnerimg} from './bnnerimg.png'
export {default as AboutImg} from './AboutImg.png'
export {default as sponserimage1} from './sponserimage1.png'
export {default as sponserimage2} from './sponserimage2.png'
export {default as sponserimage3} from './sponserimage3.png'
export {default as sponserimage4} from './sponserimage4.png'
export {default as sponserimage5} from './sponserimage5.png'
export {default as sponserimage6} from './sponserimage6.png'
export {default as sponserimage7} from './sponserimage7.png'
export {default as sponserimage8} from './sponserimage8.png'
// export {default as personimg1} from './personimg1.png'
export {default as personimg2} from './personimg2.png'
export {default as placeholderImage} from './placeholderImage.png'
